<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Confirmation_cursor-pointer</name>
   <tag></tag>
   <elementGuidId>6709a956-cad6-44c2-b17c-e8e6b808894b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sid-64409601']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0fb7b9a-9f46-4050-985f-c35aa89d8472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized1024-jpg.webp</value>
      <webElementGuid>aff6aca7-87f2-4eea-b1f3-72fd189cd731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02.jpg 2000w, https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized256-jpg.webp 256w,https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized512-jpg.webp 512w,https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized1024-jpg.webp 1024w</value>
      <webElementGuid>5984b612-5fda-47bf-8cf3-5c1804d69ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>84ec5dc8-35ab-4d5c-8e8b-a866dd827c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>54780612-7d02-4fc5-a47b-e23aef102ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>683</value>
      <webElementGuid>651d334a-8887-4e7b-b4ae-aacba71290c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sid-64409601&quot;)/div[@class=&quot;o-hidden page-section__content page-section--slideshow page-section__content--wide&quot;]/div[@class=&quot;v-responsive swiper-slide p-relative img--100w&quot;]/div[@class=&quot;v-responsive__content&quot;]/img[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>95f90f14-a87f-4af1-b7a1-cb1686dc4092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sid-64409601']/div/div/div[2]/img</value>
      <webElementGuid>80b1512f-68a1-48ae-89c2-b9058de829b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized1024-jpg.webp')]</value>
      <webElementGuid>13fe9601-34d8-465c-bd96-6805cc483d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/img</value>
      <webElementGuid>089771b2-55b5-439d-bc2b-db39cedecc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2kchovjbwl1tk.cloudfront.net/vendors/55/assets/image/1693790766924-BANNER_JOYFUL_OF_WONDERS-02_resized1024-jpg.webp']</value>
      <webElementGuid>59abc211-a918-45ac-a3dc-184f87051123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
