<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Operation Failed</name>
   <tag></tag>
   <elementGuidId>79c122a9-70dd-4cfe-a2a6-c79cf69ed1b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-alert']/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'reason' and (text() = 'Username/Password did not match' or . = 'Username/Password did not match')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>8cb7f821-b60f-4c39-bb97-c58320da96c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username/Password did not match</value>
      <webElementGuid>090ae2b0-4ec9-4ce4-91f5-ae5ec4204139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-alert']/h4</value>
      <webElementGuid>ac149572-af7f-4453-a07d-12da24989499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username/Password did not match'])[1]/preceding::h4[1]</value>
      <webElementGuid>b350b6fb-2bc9-4cf2-a683-0e7df0eb688b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>8b5d480c-274c-4409-a892-22a8886c556c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' Operation Failed' or . = ' Operation Failed')]</value>
      <webElementGuid>c1b89bed-b8d5-41b9-97b4-587162567385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
