<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Pricing</name>
   <tag></tag>
   <elementGuidId>102c0f9c-1df3-4a43-9823-8173d2987e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container > div.col-md-12 > h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pricing']/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>14f6ebd4-37fc-487b-ba7b-370ed44ad52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>ffc394c6-564f-480f-aaf0-ac0bcc729511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pricing&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12&quot;]/h2[1]</value>
      <webElementGuid>4c9eb29e-57e0-491d-85bc-9cb1b86ff748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pricing']/div/div/div/h2</value>
      <webElementGuid>1290db61-fd6e-4521-9fc3-49e95052174b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='melayani customer 24jam non stop dengan respon time hitungan detik'])[1]/following::h2[1]</value>
      <webElementGuid>0c7337c3-1c00-4419-b3e3-b6ae7ae32e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minta Resi'])[1]/following::h2[1]</value>
      <webElementGuid>5e253df9-135d-4843-bf5a-b44890ab3306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konsultasi'])[1]/preceding::h2[1]</value>
      <webElementGuid>9ecea618-d8d7-403a-9e10-5d29a6011246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[2]/preceding::h2[1]</value>
      <webElementGuid>36ea93dd-9359-4d5c-820f-7e34af65bef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing']/parent::*</value>
      <webElementGuid>42941798-1990-48a9-871b-3d49e7808f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/h2</value>
      <webElementGuid>06c67e5e-2f01-4882-9bec-dc254a35ec75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>b64180a0-37f4-4812-befc-5b91d441efb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
