<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_hos-id.com_img-responsive fiture-img im_3629ea</name>
   <tag></tag>
   <elementGuidId>2a295c0a-0e7f-4f00-9eb6-3cf9e819a2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fiture-row']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.fiture-img.img-transparent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e2599d2b-d72e-403d-881a-300990f1ecfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sistemtoko.com/img/fitur/porto4.jpg</value>
      <webElementGuid>5432a83c-097e-4ace-9572-60ebc70d89f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive fiture-img img-transparent</value>
      <webElementGuid>20457f08-9dc9-4de1-886f-ddb7e907c194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sistemtoko</value>
      <webElementGuid>62fbfb31-45f5-4780-9b8c-13f3eacfd2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;siskofrontend&quot;]/div[@id=&quot;other fiture&quot;]/div[@id=&quot;list-fitur&quot;]/div[@id=&quot;fiture-row&quot;]/div[@class=&quot;col-md-4 col-sm-6 fiture-box&quot;]/a[1]/img[@class=&quot;img-responsive fiture-img img-transparent&quot;]</value>
      <webElementGuid>a9aa02d3-b35c-485a-9523-adb17fd6b795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fiture-row']/div/a/img</value>
      <webElementGuid>5c554ecd-f02e-4287-aa74-f217771604e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sistemtoko']</value>
      <webElementGuid>676a0ab0-4021-4a90-ae43-fc044c4cf7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/a/img</value>
      <webElementGuid>925db3c4-babf-497f-93b5-63931d5874b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sistemtoko.com/img/fitur/porto4.jpg' and @alt = 'Sistemtoko']</value>
      <webElementGuid>d2e325f7-1ad3-4571-a5a6-b2bf6e221a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
